### ISSUE TITLE
Scrum Meeting Pictures

### ISSUE THREAD

**Issue by mihaidan** [power10dan/tldrResearchPaper#10]
Some pictures show up upside down, and I'm not sure why. I put the pictures in my access folder, and imported them from there. Is there a better way to do this and not have them show up upside down?

**Comment by doyougnu** [comment]
You could try to upload these to google photos. If any are rotated then you could manually unrotate them, there are only 13 (cuz I took 2) so it will be boring, but won't be long

**Comment by mihaidan** [comment]
I guess they weren’t loading right.
