### ISSUE TITLE
User Creation input box does not disappear after `Create Account` is clicked

### ISSUE THREAD

**Issue by doyougnu** [power10dan/tldrResearchPaper#16]
# Expected Behavior
The user clicks "Create Account", the create account input box pops up, the user enters their data and the input box closes returning them to the login screen

# Actual Behavior
The create account input box is not destroyed after the user clicks "create account"

**Comment by power10dan** [comment]
This is fixed in 6d0c22963e99489b2959e2ed61cbef49342abf6. Closing this issue now.
