### ISSUE TITLE
User cannot use the Enter key to submit login information

### ISSUE THREAD

**Issue by doyougnu** [power10dan/tldrResearchPaper#17]
# Expected Behavior
At the login screen, the user inputs their login information and clicks enter. The user is then logged in if their credentials are valid

# Actual Behavior
At the logic screen, the user inputs their login information and clicks enter, nothing happens. In order to login the user must actually click the "Login" button

**Comment by power10dan** [comment]
This is fixed in commit 6d0c22963e99489b2959e2ed61cbef49342abf6. Closing this issue now.

**Comment by doyougnu** [comment]
This is not fixed.
