### ISSUE TITLE
"You have successfully Logged in" Box is permenant

### ISSUE THREAD

**Issue by doyougnu** [power10dan/tldrResearchPaper#18]
# Expected Behavior
When a user successfully logs in, a pop appears showing the message "You have successfully Logged in", after a few seconds, the box disappears

# Actual Behavior
The popup box appears, the message in the box is intact, but the box never disappears and is consistent for the entire user session.

**Comment by power10dan** [comment]
Fixed in commit 9bfa58b091c0c37477889675df941649fc992a57, should probably run it with more tests before I close this issue

**Comment by power10dan** [comment]
Closing this issue, as problem has been fixed.
