### ISSUE TITLE
Upload Files does not communicate success or failure to user

### ISSUE THREAD

**Issue by doyougnu** [power10dan/tldrResearchPaper#19]
# Expected Behavior
When a user uploads a file, the user receives a popup message detailing that the file was successfully uploaded

# Actual Behavior
A user uploads a file, the file window closes, and the user receives no response regarding the success or failure of the file upload.

**Comment by power10dan** [comment]
This is also done in commit 9bfa58b091c0c37477889675df941649fc992a57, albeit we haven't test it yet.

**Comment by power10dan** [comment]
Fixed in commit 6d0c22963e99489b2959e2ed61cbef49342abf6. Closing this issue now.
