### ISSUE TITLE
Upload Files calls getAllFiles

### ISSUE THREAD

**Issue by doyougnu** [power10dan/tldrResearchPaper#20]
# Expected Behavior
A user selects upload a file, the front end dispatches the request to the backend along with the file and the backend handles the request.

# Actual Behavior
The expected behavior occurs, and then the front end calls a GET request to get all of the files available in the backend. These calls should be separated into different UI Components

**Comment by power10dan** [comment]
Fixed in d3f85197361bebecd1c9ae97b046ea64630cc49d. Closing this issue.
