### ISSUE TITLE
Long paper titles push buttons off card

### ISSUE THREAD

**Issue by borkarra** [power10dan/tldrResearchPaper#38]
It looks like if a paper has a long title, the download and add summary buttons get pushed off the card. It looks like we will need to truncate titles so this does not happen.
![image](https://user-images.githubusercontent.com/24596175/32922806-f61bb8f2-cae8-11e7-91bd-26816fe42c5d.png)

**Comment by borkarra** [comment]
The paper that caused this issue: https://sites.hks.harvard.edu/jeffreyliebman/ExplainingTrendsInSNAPEnrollmentAugust2013.pdf

GROBID is putting the authors in the title as well, and unfortunately the reference used for the title also gets it's footnote thrown in the title by GROBID as well.

**Comment by power10dan** [comment]
I think this is more of a design issue rather than a GROBID issue. I think we have some ideas on mitigating this issue threw redesigning the card component, but I am not sure if we had a consensus on how to fix this error.
