### ISSUE TITLE
Set Github to only allow merges to master from branches that are sync'd

### ISSUE THREAD

**Issue by doyougnu** [power10dan/tldrResearchPaper#8]
Please enable master to be a protected branch so that we cannot merge into it without a sync. [Here](https://help.github.com/articles/about-protected-branches/) is information on what protected branches enable/disable and why we might want them. [Here](https://help.github.com/articles/configuring-protected-branches/) is how to select the branch or branches in our repository to become protected.

**ONLY DAN CAN DO THIS BECAUSE HE IS THE REPO ADMIN**

**Comment by power10dan** [comment]
Problem solved. Got Master Protected
